[project]
name = "gym-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.0",
    "pydantic-settings==2.11.0",
    "sqlmodel==0.0.27",
    "uvicorn>=0.38.0",
]
